-- MySQL Script generated by MySQL Workbench
-- Пят 20 сак 2020 15:11:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema userStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userStore` DEFAULT CHARACTER SET utf8 ;
USE `userStore` ;

-- -----------------------------------------------------
-- Table `userStore`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userStore`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('user', 'admin', 'superAdmin') NOT NULL,
  `secret` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userStore`.`key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userStore`.`key` (
  `key` CHAR(40) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
